import { PatientData, RiskResult, FIELD_RANGES } from "./riskCalculator";

function drawText(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, opts?: { font?: string; color?: string; align?: CanvasTextAlign }) {
  ctx.font = opts?.font || "12px sans-serif";
  ctx.fillStyle = opts?.color || "#1e293b";
  ctx.textAlign = opts?.align || "left";
  ctx.fillText(text, x, y);
  ctx.textAlign = "left";
}

export function generatePDFReport(data: PatientData, result: RiskResult, patientId: string | null) {
  const W = 595; // A4 width in points
  const H = 842;
  const canvas = document.createElement("canvas");
  canvas.width = W * 2;
  canvas.height = H * 2;
  const ctx = canvas.getContext("2d")!;
  ctx.scale(2, 2);

  // Background
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, W, H);

  // Header bar
  ctx.fillStyle = "#0F172A";
  ctx.fillRect(0, 0, W, 70);
  drawText(ctx, "DiabetAI", 40, 38, { font: "bold 22px sans-serif", color: "#0D9488" });
  drawText(ctx, "Clinical Diagnostic Report", 40, 56, { font: "12px sans-serif", color: "#94a3b8" });
  drawText(ctx, new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }), W - 40, 44, { font: "11px sans-serif", color: "#94a3b8", align: "right" });

  let y = 100;

  // Patient ID & Risk
  if (patientId) {
    drawText(ctx, `Patient ID: ${patientId}`, 40, y, { font: "bold 14px sans-serif" });
    y += 24;
  }

  const riskColors = { High: "#ef4444", Moderate: "#f59e0b", Low: "#0D9488" };
  const riskColor = riskColors[result.level];

  // Risk badge
  ctx.fillStyle = riskColor;
  const badgeW = 200;
  const badgeH = 40;
  const badgeX = 40;
  ctx.beginPath();
  ctx.roundRect(badgeX, y, badgeW, badgeH, 8);
  ctx.fill();
  drawText(ctx, `${result.level} Risk — ${result.percentage}%`, badgeX + badgeW / 2, y + 26, { font: "bold 16px sans-serif", color: "#ffffff", align: "center" });
  y += badgeH + 16;

  drawText(ctx, result.summary, 40, y, { font: "12px sans-serif", color: "#475569" });
  y += 32;

  // Divider
  ctx.fillStyle = "#e2e8f0";
  ctx.fillRect(40, y, W - 80, 1);
  y += 20;

  // Patient Data Table
  drawText(ctx, "Patient Biomarkers", 40, y, { font: "bold 14px sans-serif", color: "#0F172A" });
  y += 24;

  // Table header
  ctx.fillStyle = "#f1f5f9";
  ctx.fillRect(40, y - 4, W - 80, 22);
  drawText(ctx, "Biomarker", 50, y + 12, { font: "bold 10px sans-serif", color: "#64748b" });
  drawText(ctx, "Value", 280, y + 12, { font: "bold 10px sans-serif", color: "#64748b", align: "right" });
  drawText(ctx, "Reference Range", 420, y + 12, { font: "bold 10px sans-serif", color: "#64748b", align: "right" });
  y += 28;

  const fields = Object.keys(FIELD_RANGES) as (keyof PatientData)[];
  fields.forEach((key, i) => {
    const info = FIELD_RANGES[key];
    const value = data[key];
    if (i % 2 === 0) {
      ctx.fillStyle = "#f8fafc";
      ctx.fillRect(40, y - 4, W - 80, 20);
    }
    drawText(ctx, info.label, 50, y + 10, { font: "11px sans-serif" });
    drawText(ctx, `${value}${info.unit ? " " + info.unit : ""}`, 280, y + 10, { font: "bold 11px sans-serif", align: "right" });
    drawText(ctx, `${info.min} – ${info.max}${info.unit ? " " + info.unit : ""}`, 420, y + 10, { font: "11px sans-serif", color: "#94a3b8", align: "right" });
    y += 22;
  });

  y += 16;
  ctx.fillStyle = "#e2e8f0";
  ctx.fillRect(40, y, W - 80, 1);
  y += 20;

  // Feature Contributions
  drawText(ctx, "Risk Factor Contributions", 40, y, { font: "bold 14px sans-serif", color: "#0F172A" });
  y += 24;

  const sorted = [...result.featureContributions].sort((a, b) => b.contribution - a.contribution);
  const maxContrib = sorted[0]?.contribution || 1;
  const barMaxW = 200;

  sorted.forEach((c) => {
    const labels: Record<string, string> = { glucose: "Glucose", hba1c: "HbA1c", bmi: "BMI", bloodPressure: "Blood Pressure", insulin: "Insulin", age: "Age" };
    const label = labels[c.name] || c.name;
    drawText(ctx, label, 50, y + 12, { font: "11px sans-serif" });

    // Bar
    const barW = (c.contribution / maxContrib) * barMaxW;
    ctx.fillStyle = riskColor + "33";
    ctx.beginPath();
    ctx.roundRect(180, y, barW, 16, 4);
    ctx.fill();
    ctx.fillStyle = riskColor;
    ctx.beginPath();
    ctx.roundRect(180, y, barW, 16, 4);
    ctx.globalAlpha = 0.7;
    ctx.fill();
    ctx.globalAlpha = 1;

    drawText(ctx, (c.contribution * 100).toFixed(1) + "%", 180 + barW + 8, y + 12, { font: "bold 10px sans-serif", color: riskColor });
    y += 24;
  });

  y += 20;

  // Footer
  ctx.fillStyle = "#f1f5f9";
  ctx.fillRect(0, H - 50, W, 50);
  drawText(ctx, "⚠ Advisory tool only — results must be reviewed by a qualified healthcare professional.", W / 2, H - 24, { font: "10px sans-serif", color: "#64748b", align: "center" });
  drawText(ctx, "Generated by DiabetAI Clinical Decision Support System", W / 2, H - 10, { font: "9px sans-serif", color: "#94a3b8", align: "center" });

  // Convert to PDF-like download (using canvas to blob)
  const link = document.createElement("a");
  link.download = `DiabetAI_Report_${patientId || "unknown"}_${new Date().toISOString().slice(0, 10)}.png`;
  link.href = canvas.toDataURL("image/png");
  link.click();
}
